-- 200 curated German A1 words. Idempotent: re-running clears and reinserts.
-- Cascades to user_cards, so only re-run before real user data exists.

delete from public.words;

insert into public.words (german, english, gender, part_of_speech, example_de, example_en) values

-- Pronouns
('ich', 'I', null, 'pronoun', 'Ich bin müde.', 'I am tired.'),
('du', 'you', null, 'pronoun', 'Du bist nett.', 'You are nice.'),
('er', 'he', null, 'pronoun', 'Er heißt Peter.', 'He is called Peter.'),
('sie', 'she / they', null, 'pronoun', 'Sie ist Lehrerin.', 'She is a teacher.'),
('es', 'it', null, 'pronoun', 'Es regnet.', 'It is raining.'),
('wir', 'we', null, 'pronoun', 'Wir wohnen hier.', 'We live here.'),
('ihr', 'you (plural)', null, 'pronoun', 'Ihr seid Freunde.', 'You are friends.'),
('Sie', 'you (formal)', null, 'pronoun', 'Wie heißen Sie?', 'What is your name?'),

-- Verbs
('sein', 'to be', null, 'verb', 'Ich bin Student.', 'I am a student.'),
('haben', 'to have', null, 'verb', 'Ich habe einen Hund.', 'I have a dog.'),
('werden', 'to become', null, 'verb', 'Es wird kalt.', 'It is getting cold.'),
('können', 'can / be able to', null, 'verb', 'Ich kann Deutsch sprechen.', 'I can speak German.'),
('müssen', 'must / have to', null, 'verb', 'Ich muss arbeiten.', 'I have to work.'),
('wollen', 'to want', null, 'verb', 'Ich will Kaffee.', 'I want coffee.'),
('sollen', 'should', null, 'verb', 'Du sollst schlafen.', 'You should sleep.'),
('dürfen', 'may / be allowed', null, 'verb', 'Darf ich fragen?', 'May I ask?'),
('mögen', 'to like', null, 'verb', 'Ich mag Musik.', 'I like music.'),
('machen', 'to make / do', null, 'verb', 'Was machst du?', 'What are you doing?'),
('gehen', 'to go', null, 'verb', 'Ich gehe nach Hause.', 'I am going home.'),
('kommen', 'to come', null, 'verb', 'Ich komme aus Berlin.', 'I come from Berlin.'),
('sehen', 'to see', null, 'verb', 'Ich sehe dich.', 'I see you.'),
('hören', 'to hear', null, 'verb', 'Ich höre Musik.', 'I hear music.'),
('sprechen', 'to speak', null, 'verb', 'Sprichst du Englisch?', 'Do you speak English?'),
('lernen', 'to learn', null, 'verb', 'Ich lerne Deutsch.', 'I am learning German.'),
('arbeiten', 'to work', null, 'verb', 'Er arbeitet im Büro.', 'He works in the office.'),
('wohnen', 'to live', null, 'verb', 'Ich wohne in München.', 'I live in Munich.'),
('heißen', 'to be called', null, 'verb', 'Ich heiße Anna.', 'My name is Anna.'),
('essen', 'to eat', null, 'verb', 'Ich esse Brot.', 'I eat bread.'),
('trinken', 'to drink', null, 'verb', 'Ich trinke Wasser.', 'I drink water.'),
('schlafen', 'to sleep', null, 'verb', 'Das Kind schläft.', 'The child is sleeping.'),
('lesen', 'to read', null, 'verb', 'Ich lese ein Buch.', 'I am reading a book.'),
('schreiben', 'to write', null, 'verb', 'Sie schreibt einen Brief.', 'She is writing a letter.'),
('verstehen', 'to understand', null, 'verb', 'Ich verstehe nicht.', 'I do not understand.'),
('fragen', 'to ask', null, 'verb', 'Ich frage den Lehrer.', 'I ask the teacher.'),
('antworten', 'to answer', null, 'verb', 'Bitte antworte mir.', 'Please answer me.'),

-- Family
('Vater', 'father', 'der', 'noun', 'Mein Vater ist alt.', 'My father is old.'),
('Mutter', 'mother', 'die', 'noun', 'Meine Mutter kocht.', 'My mother is cooking.'),
('Kind', 'child', 'das', 'noun', 'Das Kind spielt.', 'The child is playing.'),
('Bruder', 'brother', 'der', 'noun', 'Ich habe einen Bruder.', 'I have a brother.'),
('Schwester', 'sister', 'die', 'noun', 'Meine Schwester heißt Lisa.', 'My sister is called Lisa.'),
('Familie', 'family', 'die', 'noun', 'Meine Familie ist groß.', 'My family is big.'),
('Mann', 'man / husband', 'der', 'noun', 'Der Mann ist nett.', 'The man is nice.'),
('Frau', 'woman / wife', 'die', 'noun', 'Die Frau liest.', 'The woman is reading.'),
('Freund', 'friend (m)', 'der', 'noun', 'Er ist mein Freund.', 'He is my friend.'),
('Freundin', 'friend (f)', 'die', 'noun', 'Sie ist meine Freundin.', 'She is my friend.'),

-- Home
('Haus', 'house', 'das', 'noun', 'Das Haus ist neu.', 'The house is new.'),
('Wohnung', 'apartment', 'die', 'noun', 'Die Wohnung ist klein.', 'The apartment is small.'),
('Zimmer', 'room', 'das', 'noun', 'Das Zimmer ist hell.', 'The room is bright.'),
('Küche', 'kitchen', 'die', 'noun', 'Die Küche ist sauber.', 'The kitchen is clean.'),
('Bad', 'bathroom', 'das', 'noun', 'Das Bad ist links.', 'The bathroom is on the left.'),
('Tisch', 'table', 'der', 'noun', 'Der Tisch ist groß.', 'The table is big.'),
('Stuhl', 'chair', 'der', 'noun', 'Der Stuhl ist bequem.', 'The chair is comfortable.'),
('Bett', 'bed', 'das', 'noun', 'Das Bett ist weich.', 'The bed is soft.'),
('Fenster', 'window', 'das', 'noun', 'Das Fenster ist offen.', 'The window is open.'),
('Tür', 'door', 'die', 'noun', 'Die Tür ist geschlossen.', 'The door is closed.'),
('Schrank', 'cupboard', 'der', 'noun', 'Der Schrank ist voll.', 'The cupboard is full.'),
('Lampe', 'lamp', 'die', 'noun', 'Die Lampe ist an.', 'The lamp is on.'),

-- Food and drink
('Wasser', 'water', 'das', 'noun', 'Ich trinke Wasser.', 'I drink water.'),
('Brot', 'bread', 'das', 'noun', 'Das Brot ist frisch.', 'The bread is fresh.'),
('Käse', 'cheese', 'der', 'noun', 'Der Käse ist gut.', 'The cheese is good.'),
('Milch', 'milk', 'die', 'noun', 'Die Milch ist kalt.', 'The milk is cold.'),
('Kaffee', 'coffee', 'der', 'noun', 'Ich mag Kaffee.', 'I like coffee.'),
('Tee', 'tea', 'der', 'noun', 'Der Tee ist heiß.', 'The tea is hot.'),
('Bier', 'beer', 'das', 'noun', 'Ein Bier, bitte.', 'One beer, please.'),
('Wein', 'wine', 'der', 'noun', 'Der Wein ist rot.', 'The wine is red.'),
('Apfel', 'apple', 'der', 'noun', 'Der Apfel ist süß.', 'The apple is sweet.'),
('Fleisch', 'meat', 'das', 'noun', 'Ich esse kein Fleisch.', 'I do not eat meat.'),
('Fisch', 'fish', 'der', 'noun', 'Der Fisch ist frisch.', 'The fish is fresh.'),
('Ei', 'egg', 'das', 'noun', 'Ein Ei zum Frühstück.', 'An egg for breakfast.'),
('Suppe', 'soup', 'die', 'noun', 'Die Suppe ist heiß.', 'The soup is hot.'),
('Salat', 'salad', 'der', 'noun', 'Der Salat ist grün.', 'The salad is green.'),

-- Time
('Tag', 'day', 'der', 'noun', 'Der Tag ist lang.', 'The day is long.'),
('Woche', 'week', 'die', 'noun', 'Die Woche beginnt.', 'The week is starting.'),
('Monat', 'month', 'der', 'noun', 'Der Monat ist vorbei.', 'The month is over.'),
('Jahr', 'year', 'das', 'noun', 'Das Jahr ist neu.', 'The year is new.'),
('Stunde', 'hour', 'die', 'noun', 'Eine Stunde später.', 'One hour later.'),
('Minute', 'minute', 'die', 'noun', 'Warte eine Minute.', 'Wait a minute.'),
('Zeit', 'time', 'die', 'noun', 'Ich habe keine Zeit.', 'I have no time.'),
('heute', 'today', null, 'adverb', 'Heute ist Montag.', 'Today is Monday.'),
('gestern', 'yesterday', null, 'adverb', 'Gestern war schön.', 'Yesterday was nice.'),
('morgen', 'tomorrow', null, 'adverb', 'Morgen ist Samstag.', 'Tomorrow is Saturday.'),

-- Body
('Kopf', 'head', 'der', 'noun', 'Mein Kopf tut weh.', 'My head hurts.'),
('Hand', 'hand', 'die', 'noun', 'Gib mir deine Hand.', 'Give me your hand.'),
('Fuß', 'foot', 'der', 'noun', 'Mein Fuß ist kalt.', 'My foot is cold.'),
('Auge', 'eye', 'das', 'noun', 'Ihr Auge ist blau.', 'Her eye is blue.'),
('Ohr', 'ear', 'das', 'noun', 'Das Ohr hört Musik.', 'The ear hears music.'),
('Mund', 'mouth', 'der', 'noun', 'Mach den Mund auf.', 'Open your mouth.'),
('Nase', 'nose', 'die', 'noun', 'Meine Nase läuft.', 'My nose is running.'),
('Herz', 'heart', 'das', 'noun', 'Sein Herz schlägt schnell.', 'His heart beats fast.'),
('Bauch', 'stomach', 'der', 'noun', 'Mein Bauch ist voll.', 'My stomach is full.'),
('Rücken', 'back', 'der', 'noun', 'Der Rücken schmerzt.', 'The back hurts.'),

-- City and travel
('Stadt', 'city', 'die', 'noun', 'Die Stadt ist schön.', 'The city is beautiful.'),
('Land', 'country', 'das', 'noun', 'Deutschland ist ein Land.', 'Germany is a country.'),
('Straße', 'street', 'die', 'noun', 'Die Straße ist lang.', 'The street is long.'),
('Bahnhof', 'train station', 'der', 'noun', 'Der Bahnhof ist groß.', 'The train station is big.'),
('Flughafen', 'airport', 'der', 'noun', 'Der Flughafen ist weit.', 'The airport is far.'),
('Hotel', 'hotel', 'das', 'noun', 'Das Hotel ist teuer.', 'The hotel is expensive.'),
('Zug', 'train', 'der', 'noun', 'Der Zug fährt jetzt.', 'The train leaves now.'),
('Auto', 'car', 'das', 'noun', 'Das Auto ist rot.', 'The car is red.'),
('Bus', 'bus', 'der', 'noun', 'Der Bus kommt spät.', 'The bus is coming late.'),
('Taxi', 'taxi', 'das', 'noun', 'Ich nehme ein Taxi.', 'I am taking a taxi.'),

-- Work and school
('Schule', 'school', 'die', 'noun', 'Die Schule beginnt.', 'School is starting.'),
('Universität', 'university', 'die', 'noun', 'Sie studiert an der Universität.', 'She studies at the university.'),
('Arbeit', 'work', 'die', 'noun', 'Die Arbeit ist schwer.', 'The work is hard.'),
('Büro', 'office', 'das', 'noun', 'Das Büro ist klein.', 'The office is small.'),
('Beruf', 'profession', 'der', 'noun', 'Was ist dein Beruf?', 'What is your profession?'),
('Lehrer', 'teacher', 'der', 'noun', 'Der Lehrer ist nett.', 'The teacher is nice.'),
('Student', 'student', 'der', 'noun', 'Der Student lernt viel.', 'The student learns a lot.'),
('Chef', 'boss', 'der', 'noun', 'Der Chef kommt heute.', 'The boss is coming today.'),
('Buch', 'book', 'das', 'noun', 'Das Buch ist interessant.', 'The book is interesting.'),
('Computer', 'computer', 'der', 'noun', 'Der Computer ist neu.', 'The computer is new.'),

-- Nature and weather
('Wetter', 'weather', 'das', 'noun', 'Das Wetter ist schön.', 'The weather is nice.'),
('Sonne', 'sun', 'die', 'noun', 'Die Sonne scheint.', 'The sun is shining.'),
('Regen', 'rain', 'der', 'noun', 'Der Regen ist stark.', 'The rain is strong.'),
('Schnee', 'snow', 'der', 'noun', 'Der Schnee ist weiß.', 'The snow is white.'),
('Himmel', 'sky', 'der', 'noun', 'Der Himmel ist blau.', 'The sky is blue.'),
('Baum', 'tree', 'der', 'noun', 'Der Baum ist alt.', 'The tree is old.'),
('Blume', 'flower', 'die', 'noun', 'Die Blume ist rot.', 'The flower is red.'),
('Meer', 'sea', 'das', 'noun', 'Das Meer ist ruhig.', 'The sea is calm.'),

-- Clothing
('Hemd', 'shirt', 'das', 'noun', 'Das Hemd ist weiß.', 'The shirt is white.'),
('Hose', 'trousers', 'die', 'noun', 'Die Hose ist blau.', 'The trousers are blue.'),
('Kleid', 'dress', 'das', 'noun', 'Das Kleid ist neu.', 'The dress is new.'),
('Schuh', 'shoe', 'der', 'noun', 'Der Schuh ist braun.', 'The shoe is brown.'),
('Jacke', 'jacket', 'die', 'noun', 'Die Jacke ist warm.', 'The jacket is warm.'),
('Mantel', 'coat', 'der', 'noun', 'Der Mantel ist lang.', 'The coat is long.'),

-- Colors
('rot', 'red', null, 'adjective', 'Das Auto ist rot.', 'The car is red.'),
('blau', 'blue', null, 'adjective', 'Der Himmel ist blau.', 'The sky is blue.'),
('grün', 'green', null, 'adjective', 'Das Gras ist grün.', 'The grass is green.'),
('gelb', 'yellow', null, 'adjective', 'Die Sonne ist gelb.', 'The sun is yellow.'),
('schwarz', 'black', null, 'adjective', 'Die Nacht ist schwarz.', 'The night is black.'),
('weiß', 'white', null, 'adjective', 'Der Schnee ist weiß.', 'The snow is white.'),

-- Numbers
('eins', 'one', null, 'number', 'Ich habe eins.', 'I have one.'),
('zwei', 'two', null, 'number', 'Zwei Bier, bitte.', 'Two beers, please.'),
('drei', 'three', null, 'number', 'Drei Kinder spielen.', 'Three children are playing.'),
('vier', 'four', null, 'number', 'Vier Uhr am Nachmittag.', 'Four o''clock in the afternoon.'),
('fünf', 'five', null, 'number', 'Fünf Minuten warten.', 'Wait five minutes.'),
('sechs', 'six', null, 'number', 'Sechs Tage die Woche.', 'Six days a week.'),
('sieben', 'seven', null, 'number', 'Sieben Uhr morgens.', 'Seven in the morning.'),
('acht', 'eight', null, 'number', 'Acht Stunden Arbeit.', 'Eight hours of work.'),
('neun', 'nine', null, 'number', 'Neun Bücher hier.', 'Nine books here.'),
('zehn', 'ten', null, 'number', 'Zehn Euro, bitte.', 'Ten euros, please.'),
('elf', 'eleven', null, 'number', 'Elf Minuten später.', 'Eleven minutes later.'),
('zwölf', 'twelve', null, 'number', 'Zwölf Monate im Jahr.', 'Twelve months in a year.'),
('zwanzig', 'twenty', null, 'number', 'Zwanzig Jahre alt.', 'Twenty years old.'),
('hundert', 'hundred', null, 'number', 'Hundert Euro.', 'One hundred euros.'),
('tausend', 'thousand', null, 'number', 'Tausend Menschen kommen.', 'A thousand people are coming.'),

-- Days
('Montag', 'Monday', 'der', 'noun', 'Am Montag arbeite ich.', 'On Monday I work.'),
('Dienstag', 'Tuesday', 'der', 'noun', 'Dienstag ist gut.', 'Tuesday is good.'),
('Mittwoch', 'Wednesday', 'der', 'noun', 'Am Mittwoch spiele ich.', 'On Wednesday I play.'),
('Donnerstag', 'Thursday', 'der', 'noun', 'Donnerstag ist frei.', 'Thursday is free.'),
('Freitag', 'Friday', 'der', 'noun', 'Freitag ist super.', 'Friday is great.'),
('Samstag', 'Saturday', 'der', 'noun', 'Samstag gehe ich aus.', 'On Saturday I go out.'),
('Sonntag', 'Sunday', 'der', 'noun', 'Sonntag ist ruhig.', 'Sunday is quiet.'),

-- Months
('Januar', 'January', 'der', 'noun', 'Im Januar ist es kalt.', 'In January it is cold.'),
('Februar', 'February', 'der', 'noun', 'Februar ist kurz.', 'February is short.'),
('März', 'March', 'der', 'noun', 'Im März blüht es.', 'In March things bloom.'),
('April', 'April', 'der', 'noun', 'Im April regnet es.', 'In April it rains.'),
('Mai', 'May', 'der', 'noun', 'Im Mai ist es warm.', 'In May it is warm.'),
('Juni', 'June', 'der', 'noun', 'Im Juni beginnt der Sommer.', 'In June summer begins.'),
('Juli', 'July', 'der', 'noun', 'Juli ist heiß.', 'July is hot.'),
('August', 'August', 'der', 'noun', 'Im August fahre ich weg.', 'In August I go away.'),
('September', 'September', 'der', 'noun', 'September ist mild.', 'September is mild.'),
('Oktober', 'October', 'der', 'noun', 'Im Oktober fallen Blätter.', 'In October leaves fall.'),
('November', 'November', 'der', 'noun', 'November ist grau.', 'November is grey.'),
('Dezember', 'December', 'der', 'noun', 'Im Dezember ist Weihnachten.', 'In December is Christmas.'),

-- Adjectives
('gut', 'good', null, 'adjective', 'Das Essen ist gut.', 'The food is good.'),
('schlecht', 'bad', null, 'adjective', 'Das Wetter ist schlecht.', 'The weather is bad.'),
('groß', 'big', null, 'adjective', 'Der Hund ist groß.', 'The dog is big.'),
('klein', 'small', null, 'adjective', 'Die Katze ist klein.', 'The cat is small.'),
('alt', 'old', null, 'adjective', 'Das Haus ist alt.', 'The house is old.'),
('neu', 'new', null, 'adjective', 'Das Auto ist neu.', 'The car is new.'),
('jung', 'young', null, 'adjective', 'Er ist jung.', 'He is young.'),
('schön', 'beautiful', null, 'adjective', 'Die Blume ist schön.', 'The flower is beautiful.'),
('teuer', 'expensive', null, 'adjective', 'Das Hotel ist teuer.', 'The hotel is expensive.'),
('billig', 'cheap', null, 'adjective', 'Der Wein ist billig.', 'The wine is cheap.'),
('kalt', 'cold', null, 'adjective', 'Das Wasser ist kalt.', 'The water is cold.'),
('warm', 'warm', null, 'adjective', 'Die Suppe ist warm.', 'The soup is warm.'),
('schnell', 'fast', null, 'adjective', 'Das Auto ist schnell.', 'The car is fast.'),
('langsam', 'slow', null, 'adjective', 'Der Zug ist langsam.', 'The train is slow.'),
('viel', 'much / many', null, 'adjective', 'Ich habe viel Zeit.', 'I have a lot of time.'),
('wenig', 'little / few', null, 'adjective', 'Ich habe wenig Geld.', 'I have little money.'),

-- Question words and courtesies
('ja', 'yes', null, 'particle', 'Ja, das stimmt.', 'Yes, that is right.'),
('nein', 'no', null, 'particle', 'Nein, danke.', 'No, thank you.'),
('bitte', 'please', null, 'particle', 'Bitte, hilf mir.', 'Please, help me.'),
('danke', 'thank you', null, 'particle', 'Danke schön.', 'Thank you very much.'),
('hallo', 'hello', null, 'particle', 'Hallo, wie geht es dir?', 'Hello, how are you?'),
('tschüss', 'bye', null, 'particle', 'Tschüss, bis morgen.', 'Bye, see you tomorrow.'),
('wie', 'how', null, 'question', 'Wie heißt du?', 'What is your name?'),
('was', 'what', null, 'question', 'Was machst du?', 'What are you doing?'),
('wer', 'who', null, 'question', 'Wer ist das?', 'Who is that?'),
('wo', 'where', null, 'question', 'Wo wohnst du?', 'Where do you live?'),
('wann', 'when', null, 'question', 'Wann kommst du?', 'When are you coming?'),
('warum', 'why', null, 'question', 'Warum weinst du?', 'Why are you crying?'),

-- Common adverbs
('hier', 'here', null, 'adverb', 'Ich bin hier.', 'I am here.'),
('dort', 'there', null, 'adverb', 'Er wohnt dort.', 'He lives there.'),
('jetzt', 'now', null, 'adverb', 'Ich komme jetzt.', 'I am coming now.'),
('immer', 'always', null, 'adverb', 'Ich lerne immer.', 'I always learn.'),
('nie', 'never', null, 'adverb', 'Ich rauche nie.', 'I never smoke.'),
('oft', 'often', null, 'adverb', 'Wir gehen oft ins Kino.', 'We often go to the cinema.'),
('sehr', 'very', null, 'adverb', 'Das ist sehr gut.', 'That is very good.'),
('auch', 'also', null, 'adverb', 'Ich komme auch mit.', 'I am coming along too.'),
('nur', 'only', null, 'adverb', 'Ich habe nur einen Euro.', 'I only have one euro.');
